version: "2"

linters:
  default: none  # Start with no linters, then enable specific ones
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - dupl
    - goconst
    - gocyclo
    - misspell
    - revive
    - unconvert
    - unparam
    - gosec
  settings:
    gosec:
      excludes:
        - G304  # File path from variable - acceptable in tests with t.TempDir()
        - G306  # File permissions - test files don't need strict perms
  exclusions:
    rules:
      - path: _test\.go$
        linters:
          - dupl
          - goconst

run:
  timeout: 5m
